// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

// Use environment variables or update with your new dev project URL and key
const SUPABASE_URL = "https://ibzdcrcgzeewjhpxztwh.supabase.co";
const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImliemRjcmNnemVld2pocHh6dHdoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMzkwNjEsImV4cCI6MjA2MjgxNTA2MX0.Qh36b-M8IHNhYXbV3JjBOTTjTOm6y611iQMVsVpwkTU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY);